import  * as vueTouchFeedback from './common/_feedback.js'
import './components/list/_list.js'
// import './components/list_abandoned/_list.js'
import './components/icon/_icon.js'
import './components/header/_header.js'
import './components/button/_button.js'
import './components/scroller/_scroller.js'
import './components/picker/_picker.js'
import './components/select/_select.js'
import './components/datepicker/_datepicker.js'
import './components/pagination/_pagination.js'
import './components/dropdown/_dropdown.js'
import './components/checkbox/_checkbox.js'
import './components/radio/_radio.js'
import './components/tabbar/_tabbar.js'

Vue.use(vueTouchFeedback)